---
downloads: ~/.ansible-downloads/
 
configure_dotfiles: false
configure_terminal: false
configure_osx: false
configure_vscode: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Safari
  - Messages
  - Mail
  - Plans
  - Photos
  - FaceTime
  - Calendrier
  - Contacts
  - Rappels
  - Notes
  - TV
  - Podcasts
  - Keynote
  - Numbers
  - Pages
  - Musique
  - 'App Store'
  - 'Sytem Preferences'
dockitems_persist:
  - name: "Firefox"
    path: "/Applications/Firefox.app/"
    pos: 3
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    pos: 4
  - name: "Discord"
    path: "/Applications/Discord.app/"
    pos: 5
  - name: "KeePassXC"
    path: "/Applications/KeePassXC.app/"
    pos: 6
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 7


homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - bash-completion
  - awscli
  - gettext
  - gifsicle
  - git
  - github/gh/gh
  - go
  - gpg
  - httpie
  - iperf
  - libevent
  - mcrypt
  - nmap
  - nvm
  - ssh-copy-id
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - mongodb-community
  - tmux
  - zsh
  - zsh-autosuggestions
  - zsh-completions
  - zsh-syntax-highlighting
  - zsh-history-substring-search
  - terraform
  - helm
  - kubectl


homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - mongodb/brew

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - syncthing
  - firefox
  - google-chrome
  - discord
  - keepassxc
  - chromedriver
  - docker
  - mongodb-compass
  - libreoffice
  - dropbox
  - handbrake
  - licecap
  - transmit
  - visual-studio-code
  - adobe-acrobat-reader
  - iterm2
  - rectangle
  - maccy
  - the-unarchiver
  - karabiner-elements



# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

