---
- name: "install VS Code extensions"
  command: "code --install-extension '{{ item }}'"
  with_items:
    - "{{ visual_studio_code_extensions }}"
  register: vscode_result
  changed_when: "'already installed' not in vscode_result.stdout"
